//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int BID { get; set; }
        public string Bookname { get; set; }
        public Nullable<long> Price { get; set; }
        public string Genre { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
