//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Issue
    {
        public int IID { get; set; }
        public Nullable<int> UID { get; set; }
        public Nullable<int> BID { get; set; }
        public string IssueDate { get; set; }
        public Nullable<int> NoofDays { get; set; }
        public string ExpReturnDate { get; set; }
        public string ActualReturnDate { get; set; }
        public long Fine { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
