//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LibraryWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Issues = new HashSet<Issue>();
        }
    
        public int UID { get; set; }
        public string Username { get; set; }
        public long MobNo { get; set; }
        public string Address { get; set; }
    
        public virtual ICollection<Issue> Issues { get; set; }
    }
}
